version: '3.9'

services:
  web:
    build: .
    command: npm start
    ports:
      - "3001:3000"
    environment:
      - POSTGRES_URL=postgres://postgres:3240@db:5432/learnstuff
    depends_on:
      - db
  db:
    image: 'postgres:latest'
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: learnstuff
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3240
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
